name: chopper_example
description: Example usage of the Chopper package
version: 0.0.1
documentation: https://hadrien-lejard.gitbook.io/chopper/
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^6.0.0
  chopper: ^3.0.0
  json_annotation: ^3.0.0
  built_value: ^7.0.0

dev_dependencies:
  build_runner: ^1.0.0
  chopper_generator: ^3.0.0
  build_web_compilers: ^2.0.0
  json_serializable: ^3.0.0
  built_value_generator: ^7.0.0

dependency_overrides:
 chopper:
   path: ../chopper