dart:
- stable

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .
- unit_test:
  - test: --coverage=coverage
  - test: -p chrome

cache:
  directories:
  - .dart_tool/build