dart:
- stable

stages:
- analyzer_and_format:
  - group:
    - dartfmt
    - dartanalyzer: --fatal-infos .
- ensure_build:
  - test: --run-skipped -t presubmit-only test/ensure_build_test.dart
- unit_test:
  - test:
  - test: -p chrome

cache:
  directories:
  - .dart_tool/build