# Created with package:mono_repo v3.4.7
name: Dart Lint CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - name: mono_repo self validate
        run: pub global activate mono_repo 3.4.7
      - name: mono_repo self validate
        run: pub global run mono_repo generate --validate
  job_002:
    name: "analyze; PKGS: chopper, chopper_built_value, chopper_generator; `dartanalyzer .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value-chopper_generator;commands:dartanalyzer"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value-chopper_generator
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - id: chopper_pub_upgrade
        name: "chopper; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper
        run: pub upgrade --no-precompile
      - name: chopper; dartanalyzer .
        if: "always() && steps.chopper_pub_upgrade.conclusion == 'success'"
        working-directory: chopper
        run: dartanalyzer .
      - id: chopper_built_value_pub_upgrade
        name: "chopper_built_value; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper_built_value
        run: pub upgrade --no-precompile
      - name: chopper_built_value; dartanalyzer .
        if: "always() && steps.chopper_built_value_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_built_value
        run: dartanalyzer .
      - id: chopper_generator_pub_upgrade
        name: "chopper_generator; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper_generator
        run: pub upgrade --no-precompile
      - name: chopper_generator; dartanalyzer .
        if: "always() && steps.chopper_generator_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_generator
        run: dartanalyzer .
  job_003:
    name: "analyze; PKGS: chopper, chopper_built_value, chopper_generator; `dartfmt -n --set-exit-if-changed .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@v2
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value-chopper_generator;commands:dartfmt"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;dart:stable;packages:chopper-chopper_built_value-chopper_generator
            os:ubuntu-latest;pub-cache-hosted;dart:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@v1.0
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@v2
      - id: chopper_pub_upgrade
        name: "chopper; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper
        run: pub upgrade --no-precompile
      - name: "chopper; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.chopper_pub_upgrade.conclusion == 'success'"
        working-directory: chopper
        run: dartfmt -n --set-exit-if-changed .
      - id: chopper_built_value_pub_upgrade
        name: "chopper_built_value; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper_built_value
        run: pub upgrade --no-precompile
      - name: "chopper_built_value; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.chopper_built_value_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_built_value
        run: dartfmt -n --set-exit-if-changed .
      - id: chopper_generator_pub_upgrade
        name: "chopper_generator; pub upgrade --no-precompile"
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: chopper_generator
        run: pub upgrade --no-precompile
      - name: "chopper_generator; dartfmt -n --set-exit-if-changed ."
        if: "always() && steps.chopper_generator_pub_upgrade.conclusion == 'success'"
        working-directory: chopper_generator
        run: dartfmt -n --set-exit-if-changed .
